# -*- coding: utf-8 -*-
"""中国英语老师口吻的分组顺口溜（谐音、拆词、口诀、亲切提醒）。"""

TEACHER_FAMILY = {
    "dict": "词根 dict＝说，跟着老师念：addict 天天说成了瘾，predict 提前说是预测，dictate 发号施令口述下，unpredictable 说不准——记住了吗？",
    "struct": "词根 struct＝建造：instruct 把知识建进脑＝教导，destruction 拆掉＝破坏，infrastructure 底下打地基＝基础设施，reconstruct 重新建＝重建。",
    "cess": "词根 cess＝走：excess 走过头＝过量，procession 排着队往前走，ancestor 走在前面的是祖先，predecessor 前任、successor 接班人，一路走下来就顺了。",
    "part": "词根 part＝部分：partial 只有一部分＝偏袒，impart 把知识分给你＝传授，depart 分道扬镳＝离开，particle 极小部分＝颗粒，分得清就记得牢。",
    "spec": "词根 spec＝看：specify 把细节看明白＝明确说明，specialize 专看一门＝专攻，specialty 看得最专＝专长，specification 写明的规格——划重点。",
    "spect": "词根 spect＝看：inspect 往里看＝检查，respect 回头看你＝尊重，irrespective 看都不看＝不考虑，respective 各看各的＝各自的。",
    "stat": "词根 stat＝站着：restate 站起来再说一遍＝重述，overstate 站过头＝夸大，understate 站低了＝轻描淡写，estate 立着的家产＝庄园/遗产，statistic 站着数数＝统计。",
    "tinct": "词根 tinct＝刺/区分：distinct 刺得分明＝清晰，distinctive 独一份＝独特，extinct 刺没了＝灭绝，ex＝外、不再刺了，好记吧。",
    "clud": "词根 clud＝关门：exclude 关在门外＝排除，exclusive 关起门独享＝专属，conclusive 把案子关了＝有结论，inconclusive 没关死＝无定论。",
    "form": "词根 form＝形状：conform 随大流同形＝从众，format 排好形状＝格式，formation 形状长成＝形成，uniformity 一个形状＝一致。",
    "pend": "词根 pend＝挂/付：depend 挂在他身上＝依赖，expend 把钱挂出去＝花费，independent 自己挂＝独立，interdependence 互相挂＝相互依赖。",
    "press": "词根 press＝压：depress 压下去＝沮丧/萧条，repression 压住＝压制，expressive 把感受压出来＝表达力强，irrepressible 压不住＝活力四射。",
    "tend": "词根 tend＝伸/倾向：tendency 伸向某方＝倾向，contend 伸手去争＝主张，extensive 伸得广＝广阔，tender 伸出去的柔软＝温柔的。",
    "conv": "词根 ven＝来：convention 大家一起来＝大会/惯例，conventional 按惯例的＝传统，unconventional 不按惯例＝非传统，convey 带过来＝传达/运送。",
    "log": "词根 log＝说话/记录：log 记日志，logic 说话有条理＝逻辑，catalog 一条条记录＝目录，analog 说的话相近＝类似物，联想记。",
    "migr": "词根 migr＝迁移：migrate 迁徙，e- 出去＝emigrate 移出，im- 进来＝immigrate 移入，e 外 im 内，方向别搞反。",
    "nsci": "词根 sci＝知道：conscious 知道＝有意识，subconscious 底层知道＝潜意识，unconscious 不知道＝无意识，con 加强、un 否定，记牢。",
    "produc": "词根 duc＝引导：produce 带出来＝生产，productive 能产＝高效，reproduce 再生产＝复制/繁殖，reproductive 生殖的。",
    "sign": "词根 sign＝标记：signature 亲笔标记＝签名，assign 把标记分给人＝分配，resign 交回标记＝辞职，signify 用标记表示＝表明。",
    "stitut": "词根 stitut＝站立/设立：constitute 站一起＝构成，constitution 国之基石＝宪法，constituent 构成的一份＝成分/选民，unconstitutional 违宪。",
    "vers": "词根 vers＝转：reverse 转过来＝反转，adverse 转过来对着＝有害，reversal 大反转，reversible 能转回＝可逆，verse 转着读＝诗歌。",
    "cept": "词根 cept＝拿：conception 拿进脑子＝概念，exception 拿出去＝例外，exceptional 例外级的＝卓越，misconception 拿错了＝误解。",
    "civil": "词根 civil＝公民：civilian 平民，civilize 教成文明公民＝使文明，civility 文明之举＝礼貌，civilization 文明。",
    "clin": "词根 clin＝斜：incline 倾斜/倾向，inclination 倾向，clinic 病人靠过来看＝诊所，clinical 临床的。",
    "direct": "词根 rect＝直：direct 直着指＝指导，directive 指令，indirect 不直＝间接，directory 指路之书＝目录。",
    "divid": "词根 divid＝分：division 分开/除法，divisive 制造分裂的，undivided 不分心＝专注，individually 一个一个地＝逐个。",
    "doubt": "doubt 拿不准：doubter 怀疑者，doubtful 可疑的，undoubted 不容怀疑＝无疑，undoubtedly 毫无疑问地。",
    "fect": "词根 fect＝做：infect 把病菌做进去＝传染，disinfect 把病菌做掉＝消毒，perfection 做到极致＝完美，imperfect 没做全＝不完美。",
    "gener": "词根 gener＝产生：generator 发电机，generalize 从个别生出一般＝概括，degenerate 走下坡＝退化，generative 有生成力的。",
    "grad": "词根 grad＝步：gradual 一步步的＝逐渐，upgrade 升一级＝升级，degrade 降一级＝贬低/退化，grader 分年级的学生。",
    "incid": "词根 cid＝落下：coincide 一起落下＝巧合/一致，coincidence 巧合，incidental 附带落下的＝附带，incidentally 顺便说一句。",
    "oper": "词根 oper＝干活：operate 操作，cooperate 一起干＝合作，operator 操作员，operative 生效的/特工。",
    "pass": "词根 pass＝通过：passport 通关证件，bypass 绕道通过，surpass 超过去＝超越，compass 指引方向的＝指南针。",
    "prec": "词根 prec＝掐准/在前：precede 走在前，preceding 先前的，precise 掐得很准＝精确，precision 精确度。",
    "provid": "词根 vid＝看：provide 提前看好所需＝提供，provision 提供的条款/储备，provided 在…前提下＝如果，provider 提供者。",
    "publ": "词根 publ＝公共：publicity 公开宣传，publicize 使公开，republic 公共之国＝共和国，republican 共和党的。",
    "ration": "词根 rat＝计算：rational 会算计＝理性的，irrational 不算计＝不理性，rationalize 找理由＝合理化，rationally 理性地。",
    "rupt": "词根 rupt＝断裂：abrupt 突然断＝突然的，disrupt 打断秩序＝扰乱，disruption 中断，disruptive 破坏性的。",
    "scrib": "词根 scrib＝写：prescribe 预先写好＝开药/规定，subscribe 在下面写名＝订阅，subscription 订阅，subscriber 订阅者。",
    "sens": "词根 sens＝感觉：sensible 感觉到位＝明智，sensitive 感觉多＝敏感，sensual 感官的，insensitivity 麻木不仁。",
    "soci": "词根 soci＝同伴：social 社交的，socialize 交际，socialism 社会主义，asocial 不合群的。",
    "take": "take 拿：intake 拿进去＝摄入，overtake 从后头拿＝超越，undertake 在下面接下＝承担，retake 再拿一次＝重考。",
    "tect": "词根 tect＝盖：detect 揭开盖子＝发现，detective 侦探，detection 侦测，protective 护着的＝保护性的。",
    "tempt": "词根 tempt＝试/诱：tempt 引诱，temptation 诱惑，contempt 不屑一试＝轻蔑，contemptuous 轻蔑的。",
    "termin": "词根 termin＝界限：terminate 到界＝终止，determination 定下界线＝决心，exterminate 赶到界外＝灭绝，predetermine 预先定好。",
    "terr": "词根 terr＝怕：terrify 使害怕，terrifying 吓人的，terror 恐怖，terrorism 恐怖主义，terrorist 恐怖分子。",
    "vent": "词根 vent＝来：invent 想出来＝发明，inventor 发明家，inventory 清点存货，reinvent 重新发明。",
    "-pres": "词根 press＝呈现（前缀 mis- 别搞混）：misrepresent 呈现错了＝歪曲，representative 代表，representation 代表/表现。",
    "academ": "academy 学园：academic 学术的，academia 学术界，academically 学术上——校园场景一起记。",
    "access": "词根 cess＝走：access 走过去＝进入/通道，accessible 进得去＝易接近，inaccessible 进不去，accessibility 可及性。",
    "act": "词根 act＝做：interact 互相做＝互动，interaction 互动，enact 做成法律＝颁布，overreact 做过头＝反应过度。",
    "analyt": "词根 lys＝解开：analyze 解开＝分析，analytic 分析的，analytical 解析的，analytics 分析学。",
    "auth": "词根 auth＝真实：authentic 真实可信，authenticate 验证真伪，authorization 授权，unauthorized 未经授权的。",
    "clos": "词根 clos＝关：disclose 打开盖子＝披露，disclosure 披露，enclose 围起来/附上，enclosure 围场/附件。",
    "compl": "词根 pl＝满/叠：complement 补满＝补充，complementary 互补的，complicate 叠起来＝使复杂，complicated 复杂的。",
    "cycl": "词根 cycl＝圆：cycle 循环，recycle 循环再用，recycling 回收利用，cyclist 骑自行车的人。",
    "defin": "词根 fin＝界限：define 定界＝定义，definite 界限清楚＝明确，indefinite 没界限＝无限期，redefine 重新定义。",
    "divers": "词根 vers＝转：diversify 转出多种＝多样化，diversity 多样性，diversion 转到别处＝转移/娱乐。",
    "domin": "词根 domin＝主人：dominate 当主人＝支配，dominant 主导的，predominance 占优势，predominant 主要的。",
    "effici": "词根 fic＝做：efficient 做得又快又好＝高效，efficiency 效率，inefficient 低效，inefficiency 低效——效率这件事老师天天讲。",
    "fair": "fair 公平：fairness 公平，unfair 不公平，unfairly 不公平地，unfairness 不公——un 一加，公平变不公。",
    "fortun": "fortuna 命运女神：fortunate 幸运的，fortunately 幸好，unfortunate 不幸的，misfortune 厄运。",
    "found": "found 打地基：foundation 地基/基金会，founder 奠基人/创始人，profound 深到地基＝深刻，profoundly 深刻地。",
    "front": "front 前面：confront 面对面＝对抗，confrontation 对峙，forefront 最前线，frontier 边疆/前沿。",
    "gram": "词根 gram＝写/克：program 写好的计划/程序，grammar 写作规则＝语法，kilogram 千克，programmer 程序员。",
    "grav": "词根 grav＝重：gravity 重力，grave 沉重/坟墓，engrave 刻下去＝雕刻，gravitate 被吸引过去。",
    "gress": "词根 gress＝走：progress 往前走＝进步，progressive 进步的，congress 走到一起开会＝国会，congressional 国会的。",
    "habit": "habit 习惯：habitual 习惯性的，inhabit 住进去＝居住，inhabitant 居民，habitually 惯常地。",
    "honor": "honor 荣誉：honorable 光荣的，honorably 光荣地，dishonor 使丢脸/拒付。",
    "innov": "词根 nov＝新：innovate 创新，innovation 创新，innovative 创新的，innovator 创新者。",
    "legisl": "词根 leg＝法律：legislation 立法，legislature 立法机关，legislative 立法的，legislator 立法者。",
    "liber": "词根 liber＝自由：liberal 自由的/开明的，liberalism 自由主义，liberalize 自由化，illiberal 不开明的。",
    "llect": "词根 lect＝收集：collect 收集，collective 收到一起＝集体，collector 收藏家，recollect 收回记忆＝回想。",
    "mechan": "mechan 机器：mechanic 机械师，mechanical 机械的，mechanization 机械化，mechanize 使机械化。",
    "motiv": "词根 mot＝动：motivate 推动＝激励，motivation 动机，motive 动机，demotivate 打击积极性。",
    "mpet": "词根 pet＝追求：compete 一起追＝竞争，competence 竞争的实力＝胜任，competent 能胜任的，incompetent 不胜任的。",
    "mpos": "词根 pos＝放：compose 放在一起＝组成/作曲，composite 合成的，composition 组成/作文，composure 放得稳＝镇定。",
    "nsid": "词根 sid＝坐：consider 坐下来想＝考虑，considerable 值得坐下来想的＝相当大，considerate 替人着想＝体贴，reconsider 重新考虑。",
    "pers": "词根 sist＝站：persist 一直站着＝坚持，persistence 坚持，persistent 坚持不懈的，persistently 坚持不懈地。",
    "plac": "词根 plac＝放：displace 挪走＝取代/流离，placement 安置/放置，replaceable 可替换的，replacement 替代品。",
    "plicit": "词根 plic＝折叠：explicit 摊开来讲＝明确的，implicit 折在里面＝含蓄的，explicitly 明确地，implicitly 含蓄地。",
    "regul": "regula 规则：regulate 定规则＝监管，regulator 监管者，regulatory 监管的，deregulate 松绑＝放松管制。",
    "sent": "词根 sent＝感觉/在场：absent 心不在场＝缺席，resent 感觉被刺＝怨恨，resentment 怨恨，absently 心不在焉地。",
    "settl": "settle 安顿：settlement 定居/解决，settler 定居者，unsettle 使不安——安顿好了才安心。",
    "simpl": "simpl＝简单：simplify 简化，simplicity 简单，oversimplify 过于简单化，simplification 简化。",
    "spond": "词根 spond＝回应：correspond 互相回应＝通信/相符，correspondence 通信，correspondent 记者，respondent 受访者。",
    "spons": "词根 spons＝承诺：sponsor 承诺出钱＝赞助，sponsorship 赞助，responsive 回应快的，unresponsive 没反应的。",
    "strain": "词根 strain＝拉紧：constrain 拉紧＝约束，constraint 约束，restrain 拉住＝克制，restraint 克制。",
    "stru": "词根 stru＝建造：instrument 用来演奏的器物＝乐器/仪器，instrumental 起关键作用的，instrumentalist 乐手。",
    "tegr": "词根 tegr＝完整：integrate 使完整＝整合，integration 整合，disintegrate 不完整＝瓦解，disintegration 瓦解。",
    "text": "词根 text＝编织：texture 织出的质地，textile 纺织品，textual 文本的，pretext 事先织好的借口。",
    "tinue": "词根 tin＝保持：continue 继续，continuity 连续性，continual 不断的，discontinue 中断/停售。",
    "use": "use 用：abuse 乱用＝滥用，misuse 错用，usage 用法，useless 没用的——用坏了就是 abuse。",
    "valid": "词根 val＝强/值得：valid 有效的，invalid 无效的，validate 验证，validity 有效性。",
    "visibl": "词根 vis＝看：visible 看得见的，invisible 看不见的，visibility 可见度，visibly 明显可见地。",
    "accord": "accord 心与心一致：accordance 一致，accordingly 相应地，in accord 和谐一致。",
    "adequ": "adequ 足够：adequate 足够的，adequately 充分地，inadequate 不足的——ad 加强，够够的。",
    "affect": "词根 fect＝做/影响：affect 影响，affection 深情，affectionate 有深情的，unaffected 不受影响的。",
    "affili": "affiliate 挂靠：affiliated 附属的，affiliation 隶属/入会。",
    "affirm": "词根 firm＝坚定：affirm 肯定，affirmation 肯定/宣言，reaffirm 重申——firm 本来就是“坚定”。",
    "aggress": "词根 gress＝走：aggress 走向别人＝挑衅，aggressive 好斗的，aggressiveness 攻击性。",
    "agricult": "词根 agri＝田地：agriculture 农业，agricultural 农业的，nonagricultural 非农业的。",
    "architect": "architect 建筑师：architecture 建筑，architectural 建筑的。",
    "assembl": "词根 sembl＝一起：assemble 聚到一起＝组装/集合，assembly 集会/组装，disassemble 拆开。",
    "assimil": "词根 simil＝相同：assimilate 变相同＝同化/吸收，assimilation 同化，assimilative 同化的。",
    "assur": "词根 sur＝确定：assure 使确信，assurance 保证，reassure 再宽心＝使安心。",
    "barrass": "barrass＝拦：embarrass 被拦住下不来台＝使尴尬，embarrassed 尴尬的，embarrassment 尴尬。",
    "bat": "bat 棒子/打：combat 对打＝战斗，combative 好斗的。",
    "bias": "bias 偏见：biased 有偏见的，unbiased 无偏见的——bias 带偏，un 拉正。",
    "bid": "bid 出价/命令：bidder 出价人，forbid 命令不许＝禁止。",
    "body": "body 身体：embody 使有实体＝体现，embodiment 化身/体现，bodily 身体的。",
    "case": "case 盒子/情况：cassette 盒式磁带，casual 随意的，casualness 随意。",
    "caution": "caution 小心：precaution 事先小心＝预防，precautionary 预防性的。",
    "cave": "cave 洞穴：cavity 洞/蛀牙，caveat 警告/附带条件。",
    "claim": "claim 喊：acclaim 大声叫好＝称赞，claimant 索赔人/申请人，disclaim 否认。",
    "class": "class 等级：classify 分级归类，classification 分类，reclassify 重新归类。",
    "coher": "词根 her＝粘：cohere 粘在一起＝连贯，coherent 连贯的，cohesive 有凝聚力的。",
    "colon": "colony 殖民地：colonial 殖民的，colonialism 殖民主义。",
    "count": "count 数：counter 柜台/计数器，countless 数不清的，recount 重新数/复述。",
    "cover": "cover 盖：coverage 覆盖/报道量，uncover 揭开，undercover 秘密卧底。",
    "cred": "词根 cred＝相信：credible 可信的，incredible 难以置信的，credibility 可信度。",
    "cumul": "词根 cumul＝堆积：accumulate 越堆越多＝积累，accumulation 积累，cumulative 累积的。",
    "curi": "curi＝关心：curious 好奇的，curiosity 好奇心，curiously 好奇地。",
    "defer": "词根 fer＝带：defer 往后带＝推迟/遵从，deference 尊重/顺从，deferential 恭敬的。",
    "delib": "deliberate 反复掂量＝深思熟虑/故意，deliberately 故意地，deliberation 审议。",
    "dens": "词根 dens＝密：dense 稠密的，density 密度，condense 压缩/浓缩。",
    "diagnos": "diagnose 诊断，diagnosis 诊断，diagnostic 诊断的。",
    "dimen": "dimension 维度/尺寸，dimensional 维度的，multidimensional 多维的。",
    "dispos": "dispose 处理/安排，disposal 处理，disposable 一次性的/可支配的。",
    "duct": "词根 duct＝引导：conductor 引导者/指挥，semiconductor 半导体，conducive 有助于的。",
    "due": "due 到期的：duly 按时地，overdue 过期的，undue 过度的。",
    "dulg": "dulge＝放任：indulge 放纵，indulgence 放纵/恩惠，indulgent 纵容的。",
    "dwell": "dwell 居住/细想：dweller 居民，dwelling 住宅。",
    "eager": "eager 渴望：eagerness 渴望，eagerly 热切地。",
    "ease": "ease 轻松：uneasy 不安的，unease 不安——ease 舒坦，un 一加就不舒坦。",
    "econom": "economy 经济：economical 经济的＝节约的，economically 经济上，uneconomic 不经济的。",
    "elev": "词根 lev＝升高：elevate 提升，elevator 电梯，elevation 海拔/提升。",
    "equal": "equal 平等：equality 平等，inequality 不平等，egalitarian 平等主义的。",
    "ethic": "ethic 伦理：ethical 道德的，ethically 道德上。",
    "evolv": "词根 vol＝展开：evolve 展开＝进化，evolution 进化/演变，evolutionary 进化的。",
    "face": "face 脸/面：facet 一个方面，facial 面部的，interface 交界面/接口。",
    "fascin": "fascinate 使着迷，fascinating 迷人的，fascination 迷恋。",
    "favor": "favor 好感：favorable 有利的/赞同的，unfavorable 不利的。",
    "feas": "feasible 可行的，feasibility 可行性，unfeasible 不可行的。",
    "fish": "fish 鱼：fisher 渔民，fishery 渔业，overfish 过度捕捞。",
    "fright": "fright 惊吓：frighten 使害怕，frightened 受惊的。",
    "frustr": "frustrate 使挫败，frustrated 沮丧的，frustration 挫败感。",
    "genet": "词根 gene＝基因：genetic 基因的，genetically 基因上，geneticist 遗传学家。",
    "gloom": "gloom 阴暗：gloomy 阴郁的，gloominess 阴郁。",
    "grac": "词根 grac＝优雅：grace 优雅/恩典，graceful 优雅的，gracious 亲切的。",
    "hast": "hast＝快：haste 匆忙，hasten 赶快，hasty 草率的——快就容易出错，hasty 就是草率。",
    "haust": "haust＝抽：exhaust 抽干＝耗尽/排气，exhausted 精疲力竭的，exhaustion 疲惫。",
    "hend": "词根 hend＝抓：comprehend 抓住意思＝理解，comprehensive 抓得全＝全面的，comprehension 理解力。",
    "hope": "hope 希望：hopeful 有希望的，hopeless 绝望的，hopelessly 绝望地。",
    "host": "host 主人：hostess 女主人，hostile 敌对的，hostility 敌意。",
    "humili": "词根 humil＝低：humiliate 使低人一等＝羞辱，humiliating 羞辱性的，humiliation 羞辱。",
    "indic": "词根 dic＝说/指：indicate 指出＝表明，indicator 指标，indication 迹象，indicative 指示性的。",
    "infl": "词根 fl＝吹：inflate 吹大＝膨胀，inflation 通货膨胀，inflationary 通胀的。",
    "initi": "词根 it＝走：initiate 走进去＝发起，initiation 发起/入门，initiator 发起人，initiative 主动性/倡议。",
    "inst": "inst＝站/刻：instant 站着就成＝瞬间，instantly 立即，instantaneous 即时的。",
    "intim": "intimate 亲密的/暗示，intimately 亲密地，intimation 暗示/告知。",
    "isol": "isolate 使孤立，isolated 孤立的，isolation 隔离。",
    "journ": "journ＝日：journal 日报/日志，journalism 新闻业，journalist 记者，journalistic 新闻的。",
    "just": "just 正义/正好：adjust 调正＝调整，adjustment 调整，readjust 重新调整。",
    "kin": "kin 亲属：kinship 亲属关系，akin 同类的/相似的。",
    "lingu": "词根 lingu＝语言：linguist 语言学家，linguistics 语言学，linguistic 语言的。",
    "manufact": "词根 manu＝手：manufacture 手工造＝制造，manufacturer 制造商，manufacturing 制造业。",
    "mark": "mark 标记：marked 有明显标记＝显著的，markedly 显著地，marker 标记/记号笔。",
    "mean": "mean 意思：meaningful 有意义的，meaningless 无意义的，meaningfully 有意义地。",
    "mmon": "common 共同：commonality 共性，commonness 普通，uncommon 不寻常的。",
    "mmun": "词根 mun＝共同：commune 公社/交流，communism 共产主义，communist 共产主义者。",
    "mocrat": "词根 crat＝统治：democrat 民主主义者，democratic 民主的，democratize 民主化。",
    "modern": "modern 现代：modernize 现代化，modernization 现代化，modernism 现代主义。",
    "moist": "moist 潮湿：moisture 湿气，moisturizer 保湿霜。",
    "mourn": "mourn 哀悼：mournful 悲哀的，mourning 哀悼。",
    "mpar": "词根 par＝平等/比：compare 放在一起比，comparable 可比的，comparative 比较的，comparatively 相对地。",
    "natur": "nature 自然：naturalist 博物学家，naturalistic 自然主义的，unnatural 不自然的。",
    "note": "note 记下：notable 值得记的＝显著的，notably 显著地，notify 通知。",
    "nounc": "词根 nounc＝说：pronounce 发音/宣布，pronouncement 声明，pronunciation 发音。",
    "oppress": "词根 press＝压：oppress 压着＝压迫，oppression 压迫，oppressive 压迫的/闷热的。",
    "ordin": "词根 ordin＝顺序：coordinate 排顺序＝协调，coordination 协调，subordinate 低一级＝下属/从属的。",
    "passion": "passion 激情：passionate 热情的，passionately 热情地，compassion 同悲＝同情。",
    "patron": "patron 赞助人/主顾：patronage 赞助/光顾，patronize 惠顾/屈尊俯就。",
    "pens": "词根 pens＝付/称：compensate 付还＝补偿，compensation 补偿金，compensatory 补偿的。",
    "pole": "pole 杆/极：polar 极地的/相反的，polarize 两极分化。",
    "popular": "popular 受欢迎的：popularity 人气，popularize 推广，unpopular 不受欢迎的。",
    "power": "power 力量：empower 赋予力量＝授权，empowerment 授权/增权，powerless 无力的。",
    "pract": "practice 实践：practical 实用的，practicality 实用性，impractical 不切实际的，practically 实际上。",
    "pref": "词根 fer＝带：prefer 带着向前＝更喜欢，preference 偏好，preferable 更可取的，preferably 最好。",
    "pret": "词根 pret＝解释：interpret 解释/口译，interpretation 解释，misinterpret 误解，misinterpretation 误解。",
    "prosp": "词根 sper＝希望：prosper 兴旺，prosperity 繁荣，prosperous 繁荣的。",
    "pure": "pure 纯净：purify 净化，purifier 净化器，purely 纯粹地。",
    "rage": "rage 愤怒：enrage 激怒，outrage 愤慨/暴行，outrageous 令人愤慨的。",
    "real": "real 真实：realism 现实主义，realty 不动产，unreal 不真实的。",
    "renew": "renew 更新：renewable 可再生的，renewal 更新/续期。",
    "rich": "rich 富有：enrich 使丰富，richly 丰富地，richness 丰富。",
    "right": "right 正确/权利：righteous 正直的，rightly 正确地，upright 直立的/正直的。",
    "rrect": "correct 正确：correction 改正，incorrect 不正确的，incorrectly 错误地。",
    "scarc": "scarc 少：scarce 稀少的，scarcely 几乎不，scarcity 稀缺。",
    "scholar": "scholar 学者：scholarship 奖学金/学问，scholarly 学术性的。",
    "secut": "词根 secut＝跟随：prosecute 跟着追究＝起诉，prosecution 起诉，prosecutor 检察官。",
    "see": "see 看：foresee 预先看到＝预见，foreseeable 可预见的，oversee 从上往下看＝监督。",
    "sever": "sever 严重/切断：severe 严重的，severely 严重地，severity 严重性。",
    "sharp": "sharp 锋利：sharpen 磨快，sharply 急剧地/尖锐地，sharpness 锋利。",
    "short": "short 短：shortage 短缺，shorten 缩短，shortly 不久。",
    "sight": "sight 视力/景象：insight 看进去＝洞察力，insightful 有洞察力的，foresight 远见。",
    "size": "size 尺寸：sizeable 相当大的，outsize 特大号，oversize 超大。",
    "slip": "slip 滑：slippery 滑的，slipper 拖鞋，slippage 滑动/下滑。",
    "stabl": "词根 stab＝站：stable 站得稳＝稳定，stability 稳定性，instability 不稳定，stabilize 使稳定。",
    "stall": "stall 摊位/拖延：install 安放＝安装，installation 安装，instalment 分期款/集。",
    "stress": "stress 压力：stressful 有压力的，distress 困苦/使痛苦，distressed 苦恼的。",
    "suad": "词根 suad＝劝：persuade 劝说，persuasion 说服力，persuasive 有说服力的。",
    "success": "词根 cess＝走：success 一路走到底＝成功，successive 接连的，successor 继任者。",
    "suffici": "词根 fic＝做：suffice 够用，sufficient 足够的，insufficient 不足的，sufficiently 足够地。",
    "sult": "词根 sult＝咨询：consult 咨询，consultancy 咨询公司，consultant 顾问。",
    "sustain": "词根 tain＝拿/撑：sustain 撑住＝维持，sustainable 可持续的，sustainability 可持续性。",
    "symbol": "symbol 符号：symbolize 象征，symbolic 象征性的，symbolically 象征性地。",
    "system": "system 系统：systematic 系统化的，systematically 系统地，systemic 系统性的。",
    "tail": "tail 尾巴：retail 零卖（切成小份），retailer 零售商，entail 拖着＝需要/牵涉。",
    "tellect": "词根 lect＝选/读：intellect 智力，intellectual 智力的/知识分子，intellectualize 理性化。",
    "test": "test 测试/见证：attest 作证，protest 抗议（对着喊），tester 测试者。",
    "thesis": "词根 thesis＝放：thesis 论文/论点，hypothesis 假说，synthesis 综合/合成。",
    "think": "think 想：thinker 思想家，rethink 重新思考，overthink 想太多。",
    "time": "time 时间：timely 及时的，timeless 永恒的，timer 计时器。",
    "titl": "title 标题/权利：entitle 给标题/赋予权利，entitlement 权利，subtitle 副标题。",
    "transmit": "词根 mit＝送：transmit 送过去＝传输，transmission 传输，transmissible 可传播的。",
    "tray": "tray 托盘：betray 把秘密端出去＝背叛，portray 描绘/扮演。",
    "trol": "control 控制：controllable 可控的，uncontrollable 失控的，uncontrolled 不受控的。",
    "trovers": "词根 vers＝转：controversy 转来转去吵＝争议，controversial 有争议的。",
    "trud": "词根 trud＝推：intrude 推进来＝闯入/打扰，intrusion 侵入，intrusive 打扰性的。",
    "union": "union 联合/工会：unionism 工会主义，unionist 工会成员，unionize 组织工会。",
    "utter": "utter 完全的/说出：utterance 话语，utterly 完全地。",
    "vary": "词根 vari＝变化：vary 变化，variable 可变的/变量，variance 差异，variation 变化。",
    "venue": "词根 ven＝来：venue 活动地点，avenue 大街/途径，revenue 收进来的钱＝收入。",
    "verb": "verb 动词：verbal 言语的，verbalize 用言语表达，verbally 口头地。",
    "vinc": "词根 vinc＝征服：convince 征服想法＝说服，convinced 深信不疑的，convincing 有说服力的。",
    "virtue": "virtue 美德：virtuous 有德的，virtuosity 精湛技艺。",
    "vision": "词根 vis＝看：vision 视力/愿景，supervision 监督，supervise 监督，envision 设想。",
    "volunt": "词根 volunt＝意愿：voluntary 自愿的，involuntary 不自觉的，involuntarily 不由自主地。",
    "whelm": "whelm 淹没：overwhelm 压倒/淹没，overwhelming 压倒性的，overwhelmingly 压倒性地。",
    "will": "will 意愿：willing 愿意的，willingly 甘愿地，willingness 意愿，unwilling 不情愿的。",
    "worth": "worth 值得：worthy 值得的，worthless 一文不值的，unworthy 不配的——worth 前面加 worth，值不值一看便知。",
}

TEACHER_THEME = {
    "law": "法律场景走一圈：lawsuit 打官司，verdict 下判决，penalty 罚则，guilt 有罪，innocent 清白；wrongdoing 干坏事，remedy 补救，statute 成文法——考到法律别发怵。",
    "politics": "政治大戏：elect 选举，regime 政权，diplomat 外交官，ministry 部委，parliament 议会；lobby 游说，poll 民调，reign 统治——政治词串一串。",
    "economy": "经济商圈：market 市场，invest 投资，monopoly 垄断，recession 衰退，transaction 交易；profit 利润，deficit 赤字，compete 竞争。",
    "work": "职场打工记：employ 雇佣，workforce 劳动力，workload 工作量，overtime 加班，resume 简历，vacancy 空缺；career 职业生涯，professional 专业的。",
    "education": "校园生活：curriculum 课程，diploma 文凭，faculty 教师团队，tuition 学费，seminar 研讨课，undergraduate 本科生；scholarship 奖学金。",
    "tech": "科技时代：digital 数字的，hardware 硬件，database 数据库，network 网络，telecommunication 电信；automation 自动化，innovation 创新。",
    "health": "健康医疗：diagnose 诊断，surgery 手术，therapy 治疗，immune 免疫，symptom 症状，recovery 康复；nutrient 营养，wellbeing 健康。",
    "environment": "环保卫士：pollution 污染，recycle 回收，conservation 保护，greenhouse 温室，ecosystem 生态系统，biodegradable 可降解的。",
    "psychology": "心理情绪舱：anxiety 焦虑，stress 压力，dread 恐惧，grief 悲伤，joy 喜悦；conscious 有意识，emotion 情感，mood 心情。",
    "opinion": "观点评论席：evaluate 评估，criticize 批评，prejudice 偏见，viewpoint 观点，skeptic 怀疑者；objective 客观，subjective 主观。",
    "change": "变化进行时：transform 改造，convert 转换，modify 修改，reform 改革，evolve 演变；shift 转变，transition 过渡。",
    "increase": "增减跷跷板：increase 增加，decrease 减少，boost 提升，decline 下降，expand 扩大，shrink 缩小；skyrocket 飙升。",
    "important": "重要核心圈：essential 必要的，crucial 关键的，vital 至关重要的，primary 首要的，significant 重大的；priority 优先。",
    "difficulty": "困难障碍跑：obstacle 障碍，hurdle 跨栏/难关，complexity 复杂性，confusion 困惑，fragile 脆弱的；setback 挫折。",
    "success": "成败两重天：achieve 实现，attain 达成，conquer 征服，culminate 达到顶点，milestone 里程碑；fruition 成果。",
    "begin_end": "起止钟摆：commence 开始，initiate 发起，originate 起源，trigger 触发；cease 停止，terminate 终止，suspend 暂停，expire 到期。",
    "agree": "同意反对谱：consent 同意，approve 批准，endorse 支持，tolerate 容忍；oppose 反对，veto 否决，boycott 抵制，revolt 反抗。",
    "think": "思维运转中：consider 考虑，ponder 深思，contemplate 沉思，assume 假定，infer 推断；logic 逻辑，premise 前提。",
    "speak": "开口表达场：express 表达，declare 宣布，allege 宣称，confess 承认，concede 让步承认；quarrel 争吵。",
    "see": "观察者视角：observe 观察，perceive 察觉，scrutinize 细查，surveillance 监视，spectacle 奇观；subtle 微妙的。",
    "listen": "倾听专注力：attentive 专心的，overhear 无意听到，spotlight 聚光灯，noteworthy 值得注意的；indifferent 漠不关心。",
    "move": "移动旅行线：transport 运输，migrate 迁徙，wander 漫游，voyage 航行，evacuate 疏散；transit 过境，roam 闲逛。",
    "take_give": "拿取给予手：obtain 获得，seize 抓住，snatch 夺取，occupy 占据；confer 授予，endow 赋予，furnish 提供，dedicate 奉献。",
    "build": "建造破坏锤：construct 建造，establish 建立，comprise 构成，craft 精心制作；destroy 摧毁，demolish 拆除，crumble 崩塌。",
    "connect": "连接分离线：connect 连接，combine 结合，unite 团结，integrate 整合，bond 联结；detach 分离，fracture 断裂。",
    "protect": "保护伤害盾：protect 保护，defend 防御，shield 庇护，preserve 保存；harm 伤害，assault 袭击，threat 威胁。",
    "help": "助力阻碍网：assist 协助，foster 培养，promote 促进，recruit 招募，encourage 鼓励；hinder 阻碍，inhibit 抑制。",
    "time": "时间流逝钟：duration 持续，era 时代，chronological 按时间的，permanent 永久的，temporary 临时的；postpone 推迟，obsolete 过时。",
    "space": "空间方位图：location 位置，interior 内部，fringe 边缘，proximity 邻近，latitude 纬度；orbit 轨道，spectrum 范围。",
    "amount": "数量程度秤：amount 数量，abundance 丰富，sufficient 足够的，deficiency 缺乏，portion 份额；proportion 比例。",
    "size": "大小形状尺：magnitude 量级，gigantic 巨大的，tremendous 巨大的，altitude 高度，breadth 广度；vague 模糊的。",
    "sound": "声音交响曲：echo 回声，whisper 耳语，yell 喊叫，vocal 嗓音的，melody 旋律；harsh 刺耳的，eloquent 雄辩的。",
    "food": "饮食农业园：harvest 收获，crop 庄稼，herb 草药，cereal 谷物，beverage 饮料，nutrition 营养；hunger 饥饿。",
    "family": "家庭社会圈：household 家庭，offspring 后代，parenthood 父母身份，marital 婚姻的，welfare 福利；sociology 社会学。",
    "military": "军事演练场：deploy 部署，strategic 战略的，conquest 征服，maneuver 演习，troop 军队；lure 引诱。",
    "art": "艺术文化厅：sculpture 雕塑，chorus 合唱，dramatist 剧作家，heritage 遗产，legacy 遗产；flourish 繁荣。",
    "city": "城市建筑图：metropolitan 大都市的，outskirts 郊区，populate 居住于，ornament 装饰；rural 乡村的。",
    "traffic": "交通运输网：automobile 汽车，aviation 航空，highway 公路，railway 铁路，shipment 货运；toll 过路费，wreck 失事。",
    "water": "水与天气组：evaporate 蒸发，warmth 温暖，dissipate 消散，cozy 温馨的，intensity 强度。",
    "language": "语言文字库：dialect 方言，terminology 术语，vocabulary 词汇，translation 翻译，paraphrase 改写；rhetoric 修辞。",
    "life": "消费生活账：consumption 消费，expense 开销，purchase 购买，receipt 收据，burden 负担；misery 痛苦。",
    "theory": "抽象理论楼：concept 概念，principle 原理，hypothesis 假说，phenomenon 现象，framework 框架；universal 普遍的。",
    "money": "金钱财富库：affluent 富裕的，subsidy 补贴，allowance 零用钱，impoverished 贫困的，needy 贫困的。",
    "feel": "感知体验舱：instinct 本能，intuition 直觉，thrill 兴奋，awe 敬畏，undergo 经历；tedious 乏味的。",
    "truth": "真实虚假镜：factual 事实的，verify 核实，authentic 真实的，deceive 欺骗，fraud 欺诈；hypocrisy 虚伪。",
    "emotion2": "喜恶天平：admire 欣赏，esteem 敬重，gratitude 感激，proud 自豪；despise 鄙视，hatred 仇恨。",
    "moral": "道德品格尺：integrity 正直，conscience 良心，immoral 不道德的，wicked 邪恶的，moralist 道德家。",
    "personality": "性格万花筒：optimism 乐观，pessimism 悲观，modest 谦虚的，arrogant 傲慢的，cautious 谨慎的；temperament 气质。",
    "speed": "速度频率表：rapid 迅速的，swift 敏捷的，sluggish 迟缓的，hasty 仓促的，periodic 定期的；avalanche 雪崩。",
    "power": "权力控制阀：authority 权威，autonomy 自治，rein 缰绳/控制，tame 驯服，appease 安抚；liberty 自由。",
    "effect": "影响后果链：aftermath 后果，by-product 副产品，wreak 造成，yield 产生，resultant 由此产生的。",
    "similar": "相似差异镜：analogous 类似的，identical 完全相同的，resemble 相似，contrary 相反的，versus 与…相对；discrepancy 差异。",
    "order": "顺序排列队：sequence 顺序，subsequent 随后的，queue 队列，array 排列，ladder 阶梯。",
    "memory": "记忆仓库：memorize 记住，commemorate 纪念，memorial 纪念碑，recall 回忆，reminder 提醒物；neglect 忽视。",
    "duty": "责任誓言书：obligation 义务，pledge 誓言/保证，oath 宣誓。",
    "decision": "决策选择盘：option 选项，opt 选择，hesitate 犹豫，tentative 试探性的，guideline 准则。",
    "chance": "机会命运轮：destiny 命运，lottery 彩票，accidentally 偶然地，reckless 鲁莽的，adventurous 爱冒险的。",
    "conflict": "冲突矛盾结：friction 摩擦，tangle 纠缠，paradox 悖论，antagonistic 敌对的，trap 陷阱。",
    "energy": "能量动力源：energy 能量，momentum 势头，pulse 脉冲，inject 注入，rigorous 严格的；blossom 开花。",
    "light": "光亮影子戏：bulb 灯泡，candle 蜡烛，sunlight 阳光，shade 阴凉，lantern 灯笼。",
    "history": "历史遗迹层：historian 历史学家，fossil 化石，excavation 发掘，artifact 文物，landmark 地标。",
    "religion": "宗教信仰堂：sacred 神圣的，divine 神的，priest 神父，prayer 祈祷，salvation 救赎；feast 盛宴。",
    "math": "数学计算器：arithmetic 算术，formula 公式，computational 计算的，mathematical 数学的。",
    "science": "理化实验室：atom 原子，molecule 分子，chemist 化学家，experimentation 实验。",
    "geography": "地理版图册：territory 领土，terrain 地形，peninsula 半岛，plateau 高原，longitude 经度。",
    "sport": "体育娱乐场：athlete 运动员，stadium 体育场，tournament 锦标赛，leisure 休闲，recreation 娱乐；zeal 热情。",
    "tool": "工具材料箱：gadget 小工具，machinery 机器，mechanism 机制，cement 水泥，seal 密封。",
    "quality": "质量标准尺：standard 标准，norm 规范，criterion 标准，ritual 仪式，orthodox 正统的。",
    "method": "方法路径图：approach 方法，strategy 策略，tactic 战术，pathway 路径，recipe 配方。",
    "goal": "目标方向标：ambition 抱负，aspiration 志向，pursuit 追求，diagram 图表。",
    "body": "身体器官谱：digest 消化，tissue 组织，muscular 肌肉的，dental 牙齿的，stroke 中风/抚摸。",
    "color": "颜色透明度：transparent 透明的，transparency 透明，opaque 不透明的，clarity 清晰。",
}

TEACHER_ALIKE = {
    "affordable": "都像 afford：affordable 买得起，unaffordable 买不起，favorable 有利的，unfavorable 不利的，unavoidable 不可避免。",
    "allegiance": "al- 开头一串，逐个分清楚：allegiance 忠诚，alleviate 减轻，alliance 联盟，allowance 津贴，applicable 适用的，appliance 电器。",
    "ashore": "sh 开头漂流记：ashore 上岸，shore 海岸，shave 刮，shove 推，shade 阴凉，sore 酸痛，spare 备用，sparkle 闪耀——外形像，意思差。",
    "bloom": "b/oo/m 一家：bloom 开花，blossom 花朵，boom 繁荣，broom 扫帚，gloom 阴郁，loom 织布机/隐约出现。",
    "coexistence": "co- 共同开头：coexistence 共存，commerce 商业，commence 开始，competence 能力，compliance 遵从，complicate 使复杂。",
    "collaborate": "co 开头别混淆：collaborate 合作，cooperate 配合，comparable 可比的，compatible 兼容的，combative 好斗的，contemptible 可鄙的。",
    "compensate": "com- 前缀家族：compensate 补偿，compile 汇编，compose 组成，composite 复合的，composure 镇定，comprise 包含，compromise 妥协。",
    "conditional": "-tional 长尾巴：conditional 有条件的，conventional 传统的，conversational 口语的，constitutional 宪法的，intentional 故意的，unconditional 无条件。",
    "dedicate": "de- 开头变奏曲：dedicate 奉献，delegate 委派，delete 删除，delicate 精巧的，deplete 耗尽，deviate 偏离，duplicate 复制。",
    "deficiency": "-ficiency 效率组：deficiency 缺乏，sufficiency 充足，efficiency 效率，efficacy 效力，inefficient 低效。",
    "depression": "-ession/-ection 撞脸：depression 抑郁，recession 衰退，reception 接待，rejection 拒绝，repression 压制，retention 保留，reflection 反思。",
    "destruction": "-struction 分不清：destruction 破坏，disruption 扰乱，distraction 分心，distinction 区别，discretion 谨慎，distribution 分发。",
    "digest": "dis- 前缀串：digest 消化，disconnect 断开，discontent 不满，disgust 厌恶，disrupt 扰乱，distract 分心，distort 扭曲，distrust 不信任。",
    "discharge": "dis- 开头群：discharge 排放/出院，disclose 披露，discourse 话语，disperse 分散，dispose 处理，diverse 多样的，divorce 离婚。",
    "dominance": "-inance 易混组：dominance 支配，dominant 主导的，dominate 支配，donate 捐赠，dormant 休眠的，nominate 提名。",
    "estate": "e 开头变形记：estate 庄园/遗产，restate 重述，retake 重考，remake 翻拍，reshape 重塑，rotate 旋转，ripe 成熟。",
    "fade": "fa-/fl- 开头连：fade 褪色，fake 伪造，fame 名声，famine 饥荒，fare 车费，fate 命运，flame 火焰，flare 爆发，fume 发怒。",
    "forecast": "fore- 开头家族：forecast 预测，forefather 祖先，foremost 首要的，forester 林务员，foster 培养——fore 在前，foster 是养。",
    "foresight": "fore-/fri- 撞脸：foresight 远见，forthright 直率，fortnight 两星期，freight 货运，fright 惊吓。",
    "identification": "-ation 长词群：identification 识别，imitation 模仿，immigration 移民，implication 暗示，intimidation 恐吓，intuition 直觉。",
    "immense": "im- 开头四人组：immense 巨大的，immerse 沉浸，immune 免疫的，imperative 至关重要的，inverse 相反的。",
    "inaugurate": "ina-/inte- 开头：inaugurate 就职/开创，integrate 整合，interface 界面，interfere 干涉，intervene 干预。",
    "incentive": "in- 开头 -ive 组：incentive 激励，inclusive 包容的，insensitive 不敏感的，instructive 有教益的，intensive 集中的，inventive 有创造力的。",
    "infant": "in- 开头长串：infant 婴儿，instant 瞬间，instinct 本能，instruct 指导，instrument 仪器，intact 完好的，interact 互动。",
    "inhabit": "in- 开头 -it 组：inhabit 居住，inherent 固有的，inherit 继承，inhibit 抑制，insert 插入，invert 颠倒。",
    "kettle": "-ettle/-utter 绕口令：kettle 水壶，settle 解决，scatter 散落，shatter 打碎，shutter 快门，shuttle 穿梭，subtle 微妙，subtitle 字幕。",
    "magical": "-al 结尾撞脸：magical 神奇的，marginal 边缘的，marital 婚姻的，maximal 最大的，minimal 最小的，mineral 矿物，mortal 致命的/凡人。",
    "mentality": "-ality/-ility 长尾：mentality 心态，morality 道德，mortality 死亡率，mobility 流动性，nobility 贵族/高尚。",
    "passive": "pas- 开头组：passive 被动的，paste 粘贴，pastel 粉彩，pastime 消遣，pasture 牧场，posture 姿势。",
    "penetrate": "pe-/pro- 开头辨析：penetrate 穿透，permeate 渗透，perpetuate 使永存，persecute 迫害，prosecute 起诉，perspective 视角，provocative 挑衅的。",
    "predictable": "pre-/pro- 开头：predictable 可预测的，preferable 更可取的，presumably 大概，profitable 有利可图的。",
    "predominance": "pre-/pro- 双胞胎：predominance 优势，prominence 突出，proficiency 精通，proficient 熟练的，prominent 突出的。",
    "preoccupation": "pre- 开头 -tion：preoccupation 全神贯注，prescription 处方，presentation 展示，preservation 保存，prevention 预防，reservation 预订。",
    "rebalance": "re- 开头组：rebalance 再平衡，relevance 相关性，reliance 依赖，renaissance 文艺复兴，resemblance 相似，resistance 抵抗。",
    "remodel": "re-/rival 开头：remodel 改造，removal 移除，reveal 揭示，reversal 逆转，revival 复兴，rival 对手。",
    "sack": "s- 开头一窝：sack 麻袋/解雇，setback 挫折，shark 鲨鱼，slack 松弛，snack 零食，spark 火花，stack 堆，stalk 茎/跟踪，stark 荒凉。",
    "saturate": "-ate 结尾长词：saturate 使饱和，simulate 模拟，situate 位于，speculate 推测，stimulate 刺激，stipulate 规定。",
    "scar": "s- 开头短词：scar 伤疤，scarf 围巾，scholar 学者，soar 翱翔，solar 太阳的，sonar 声呐，sour 酸的，spur 刺激。",
    "seam": "-eam/-im 发音组：seam 接缝，skim 略读，slam 猛撞，slim 苗条，slum 贫民窟，steam 蒸汽，stem 茎/阻止。",
    "trait": "tr- 开头组：trait 特征，transient 短暂的，transit 过境，transmit 传输，transparent 透明的，transplant 移植。",
}
